export interface Laptop {
    id?: number; // Optional ID field, as it might be generated by the server
    brand: string;
    model: string;
    screenSize: number;
    ram: number;
    storage: number;
    processor: string;
    graphicsCard: string;
  }
  